#!/bin/bash
#
#	/etc/rc.d/init.d/fff_dqmtools
#
# Init file for fff_dqmtools.py
# Copy it to /etc/rc.d/init.d/fff_dqmtools
#
# chkconfig: 345 80 20
# description: FFF Monitoring daemon for DQM

# Source function library.
. /etc/rc.d/init.d/functions

# edit these for special stuff (fff_deleter, ...)
DAEMON_BIN=/opt/fff_dqmtools/fff_dqmtools.py
DAEMON_ARGS=
PIDFILE=/var/run/fff_dqmtools.pid
LOGFILE=/var/log/fff_dqmtools.log
NAME=fff_dqmtools

RETVAL=0

start() {
	echo -n "Starting $NAME daemon: "
	daemon --pidfile $PIDFILE $DAEMON_BIN --pidfile $PIDFILE --logfile $LOGFILE $DAEMON_ARGS
	RETVAL=$?
	echo

	return $RETVAL
}

stop() {
	echo -n "Stopping $NAME daemon: "
	killproc -p $PIDFILE
	RETVAL=$?
	echo

    return $RETVAL
}


restart() {
	stop
	start
}

reindex() {
	stop
	$DAEMON_BIN --reindex
	start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
reindex)
	reindex
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
status)
	status -p $PIDFILE
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=2
esac

exit $RETVAL
